export const ICONS_CONTANTS = {
	Home: 'fa-solid fa-house-flag',
	BallSoccer: 'fa-solid fa-futbol',
	Download: 'fa-solid fa-download',
	Facebook: 'fa-brands fa-facebook',
	Google: 'fa-brands fa-google',
	Plus: 'fa-solid fa-plus',
	Login: 'fa-solid fa-right-to-bracket',
	Loggout: 'fa-solid fa-right-from-bracket',
	Message: 'fa-solid fa-message',
	Question: 'fa-solid fa-circle-question',
	Trophy: 'fa-solid fa-trophy',
	Bars: 'fa-solid fa-bars',
	Xmark: 'fa-solid fa-xmark',
	User: 'fa-solid fa-user',
	EyeClosed: 'fa-solid fa-eye-slash',
	EyeOpened: 'fa-solid fa-eye',
	Lock: 'fa-solid fa-lock',
	Envelope: 'fa-solid fa-envelope',
	Phone: 'fa-solid fa-phone',
	Search: 'fa-solid fa-magnifying-glass',
	ThreeDotsHorizontal: 'fa-solid fa-ellipsis',
	Table: 'fa-solid fa-square-poll-horizontal',
	Cards: 'fa-solid fa-credit-card',
	Goal: 'fa-solid fa-bullseye',
	send: 'fa-solid fa-paper-plane',
	ANIMATIONS: {
		faBeat: ' fa-beat',
		faBeatFade: ' fa-beat-fade',
		bounce: ' fa-bounce',
		faFade: ' fa-fade',
		flip: ' fa-flip',
		shake: ' fa-shake',
		faSpin: ' fa-spin',
		faSpinReverse: ' fa-spin-reverse',
		faSpingPulse: ' fa-spin-pulse',
	},
}
